### ISSUE TITLE
keep

### ISSUE THREAD

**Issue by monty-expert** [discord/gamesdk-and-dispatch#107]
help my bot 
https://discord.com/oauth2/authorize?client_id=733287493041913877&permissions=2147483639&scope=bot

**Comment by advaith1** [comment]
As the error says, you need to verify your bot, go to https://dis.gd/bot-verification.

If, **after reading that page**, you still need help with bot verification, go to #verification-help in [Discord Developers](https://discord.gg/discord-developers).

This repo is only for the Discord GameSDK and Dispatch (hence the name gamesdk-and-dispatch), do not make issues about random things like bot verification here.

**Comment by tpcstld** [comment]
Thanks typing blob emoji.
