### ISSUE TITLE
X People you know have played it before caries over between SKUs

### ISSUE THREAD

**Issue by TheGoldenCactus11** [discord/gamesdk-and-dispatch#22]
**Describe the bug**
When looking at a store page for an SKU, where it says X people you know have played it before, it caries between SKUs

**Steps to reproduce**
1. Go to one SKU store and look at X people you know as played it before.
2. Go to another SKU and you will see exactly the same

**Expected behavior**
It should only show people that have played the SKU of the current store, not all customers of the game.

**Screenshots**
![image](https://user-images.githubusercontent.com/41830820/77238791-88731d00-6bcb-11ea-8f51-a10d8b46f173.png)

**Additional context**
It should be per SKU of how many people you know that have played it.

**Comment by Jump-Suit** [comment]
it would care over because all the SKUs are under one Application...

**Comment by TheGoldenCactus11** [comment]
@Jump-Suit should it not be sepetate? Of you have a DLC with the game, you would not want the DLC to say X people have played it if they only play the game

**Comment by msciotti** [comment]
While a reasonable suggestion, all of the data tables used to power this feature are all based at the application level, so we aren't able to swap it over to SKU-specific. This is intended behavior.
