### ISSUE TITLE
Discord does not "detect game" for Ask to Join, when that game is installed via a Store Channel

### ISSUE THREAD

**Issue by hach-que** [discord/gamesdk-and-dispatch#25]
## Describe the bug
When you click Ask to Join and the game isn't running, Discord says the "Game is not detected", even though it's in the user's library.

## Steps to reproduce

1. Go to https://discord.gg/z4ZnS3M
2. Click on Add to library
3. Repeat this process for a second test account
4. Launch the game on your first account through your Discord library
5. On your second test account, click on your account in the members list and mouse over Ask to Join

## Expected behavior
I expect Discord would know how to launch a game that has been installed through a Store channel, for Ask to Join.

## Screenshots
![image](https://user-images.githubusercontent.com/504826/77388022-17a64d80-6de3-11ea-876a-30bf80b2ce5f.png)
![image](https://user-images.githubusercontent.com/504826/77388027-1b39d480-6de3-11ea-99c4-fb09bd64e170.png)

## Additional context
This game is a beta branch (691162811602173985) of an unapproved game (426958487654891521).

**Comment by Jump-Suit** [comment]
Naturally, by detection it literally means "it isn't running", there is no feature for Ask to Join to know "oh X game is on your system, let me boot it up", this is more a feature request than bug. Cause you yourself NEED to run the game for Discord to know what to do with the Ask to Join, or Spectate.

**Comment by hach-que** [comment]
It launches fine when accepting an invite, so I'm not sure why Ask to Join shouldn't launch as well.

e.g. if I invite you to a game, and you click "Play" from your Discord DMs, it will launch the game. That behavior works today with games installed via Store channels.

**Comment by hach-que** [comment]
Seems like this is working for me now. Weird.

**Comment by msciotti** [comment]
>  there is no feature for Ask to Join to know "oh X game is on your system, let me boot it up"

This is actually incorrect. For games that you own via Discord, we know that you own them, so we know that game invites/Ask to Join can be used for that game even if you have it closed.

For other platforms, we offer the `RegisterCommand()` function to allow you set an abitrary command to the user's registry like `mygame://launch`. We also have `RegisterSteam()` which will map your app id on the user's system to `steam://run-game/<steam_app_id>` to do the same
