### ISSUE TITLE
Discord game URLs (like discord:///library/.../launch) do not immediately launch the game for beta branches

### ISSUE THREAD

**Issue by hach-que** [discord/gamesdk-and-dispatch#26]
## Describe the bug
When you click a Start Menu or Desktop shortcut with a URL like discord:///library/426958487654891521/launch, Discord doesn't launch the game. Instead, it just focuses the library.

I'm guessing this behavior is specific to beta branches, but I don't have any non-beta games in my library to test it with.

## Steps to reproduce

1. Go to https://discord.gg/z4ZnS3M
2. Click on Add to library
3. Navigate to something other than your library in Discord
4. Use the Start Menu link to try to launch the game, or create a shortcut with URL discord:///library/426958487654891521/launch and use that.
5. Discord will only focus the library, it will not launch the game.

## Additional context
This game is a beta branch (691162811602173985) of an unapproved game (426958487654891521).

**Comment by Jump-Suit** [comment]
Cannot Reproduce, Works fine for my Unity Game, is your manifest improperly setup to launch the executable?
![image](https://user-images.githubusercontent.com/26616362/77483035-37467180-6df5-11ea-9176-5865a9987c9f.png)

**Comment by hach-que** [comment]
Oh, it seems to be working now. Weird.
