### ISSUE TITLE
Discord can get into a state where it thinks you have no games in library, but the library is the only way to launch games installed via Store channels

### ISSUE THREAD

**Issue by hach-que** [discord/gamesdk-and-dispatch#27]
## Describe the bug
Discord can get into a state where it thinks you have no games in library, but the library is the only way to launch games installed via Store channels.

I don't know how Discord got into this state, but the only workaround I could find was restarting the client. Since store channels don't offer a Play button for games in the library, this effectively prevents the user from playing any games.

**Screenshots**
![image](https://user-images.githubusercontent.com/504826/77388551-8d5ee900-6de4-11ea-9676-ea1296eabe45.png)
![image](https://user-images.githubusercontent.com/504826/77388555-9059d980-6de4-11ea-8855-0b524eca3fd4.png)
![image](https://user-images.githubusercontent.com/504826/77388561-9354ca00-6de4-11ea-80e1-ae4539d73ee1.png)

## Additional context
This game is a beta branch (691162811602173985) of an unapproved game (426958487654891521).

**Comment by msciotti** [comment]
It's possible we had a minor blip in API that caused an entitlement to not be fetched, or something like that. This doesn't seem to be a prevalent bug (I haven't seen/heard of this outside this issue).

Gonna close this, but if it happens again, please do re-open.
