### ISSUE TITLE
People selling gift codes

### ISSUE THREAD

**Issue by TheGoldenCactus11** [discord/gamesdk-and-dispatch#33]
Hi, 

I recently gave someone some gift codes (3) which they said they were going to giveaway, instead, they are selling them, I need to be able to revoke these gift codes before someone gets scammed.

What can I do? I need these to be gone, any ideas?

Thanks

**Comment by LewdNeko** [comment]
If this is still a problem, I think the only thing you can do is contact Discord and request deletion of the keys. Include as much details as you can so they don't have to ask you for it.
