### ISSUE TITLE
Add an way of storing files into discord cloud

### ISSUE THREAD

**Issue by HKunogi** [discord/gamesdk-and-dispatch#35]
Would be cool to have functions similar to write / read from the storage manager, but to store files into discord cloud. You can actually build a bot, access it and send files as attachments on channels then load those files by searching it by some indexing gave into the message (following some patterns). But would be ideal to have this functionality inserted on the SDK itself. The idea would be that every application id would have an directory that would be inside the user id directory that uses it.
So "/[user]/[application]/(files)", could have some limitation to file sizes and/or limit of files, could even follow the limitation for the user account itself, like 8MB normal, 50MB nitro, or even only allow applications that has an developer license to use it, but surely would be an very welcome addition to it.

**Comment by advaith1** [comment]
Why can't you just use the existing Cloud Saves feature 🤔

**Comment by HKunogi** [comment]
You need to have the dispatch thing for it, and seems i can't just load/save any file from the cloud at anytime i want for that, it seems more like the cloud sync from steam, what i'm saying is something more like the google api that lets you save stuff into your application id into the user drive.

**Comment by msciotti** [comment]
Appreciate the feature request, but we won't be doing this. It was intentionally decided against when originally creating the SDK, as we want to make it free for everyone to use, and therefore don't want a bunch of nonsense programmatically saved to our CDNs by bad actors (which could be expensive for us). We allow you to use the StorageManager to save files locally if needed and keep them in sync with the cloud save functionality.

**Comment by shadowfox87** [comment]
Regarding this, what if a file is less than 1 MB? A file that saves personal player data. A text file.
