### ISSUE TITLE
Discord GameSDK always returns "en-US" from a User's Locale.

### ISSUE THREAD

**Issue by Jump-Suit** [discord/gamesdk-and-dispatch#4]
Even if a User switches to a different Locale in their Client, it still results in "en-US" been outputted.

**Comment by msciotti** [comment]
This occurs when you are not launching a game from our library. The behavior that we support is that when a game is launched from Discord's library, we pass a number of environment variables to your program:

* `DISCORD_ACCESS_TOKEN`
* `DISCORD_CURRENT_BRANCH`
* `DISCORD_INSTANCE_ID`
* `DISCORD_STORAGE_PATH`

Connecting to the SDK without launching this way does not pass those environment variables. We can look into supporting that.

**Comment by Jump-Suit** [comment]
That isn't the fault here... Since the GameSDK has to get the Locale from the User's Discord Client no?
I am aware of environment variables being passed. The User's Locale has nothing to do with that. It'll always return en-US even if explicitly marked in a User's Discord Client Language is different... + I have no other native way of launching my game than through Discord Library with exception to builds not pushed to discord, and my Editor.
