### ISSUE TITLE
[Feature Request] Game dev servers get a different verified badge

### ISSUE THREAD

**Issue by TheGoldenCactus11** [discord/gamesdk-and-dispatch#62]
Ok, when you see the verified tick, it would be good to see what they are verified for, as an example: 
<img width="422" alt="verified" src="https://user-images.githubusercontent.com/41830820/80837888-9fa42200-8bef-11ea-82a6-d50b4c2e8591.png">
No, I am not trolling, I can't draw, but it gives my idea, the blue circle, with a game controller inside, when hovered on, it will say `verified game server`, this badge will be granted to a server upon getting verified.

**Comment by advaith1** [comment]
The actual verified badge is mostly for game servers anyway (it was originally only for game servers and then they expanded it a bit); what's the point of changing the badge on most verified servers?
