### ISSUE TITLE
Bug with confirmation gmail

### ISSUE THREAD

**Issue by Wenles** [discord/gamesdk-and-dispatch#67]
If I create a discord account based on gmail and try to confirm mail, the letter does not come, I tried many times and I think it's a bug
1.My account is not verified and I'm trying to confirm it ![Screenshot_1228](https://user-images.githubusercontent.com/65066551/81468938-19896c00-91eb-11ea-8838-1d915cb1e7be.png)
2.I send a letter to my gmail mail 
![Screenshot_1229](https://user-images.githubusercontent.com/65066551/81468995-56edf980-91eb-11ea-93b7-af15f91c9159.png)
3. 
As a result, nothing has come to me for several days and I tried to do this several times
![Screenshot_1227](https://user-images.githubusercontent.com/65066551/81469042-843aa780-91eb-11ea-9e56-5d6f5e9c80b2.png)

I think this is a discord bug where it is impossible to confirm gmail mail, please solve this problem! Here is my main mail 

- [ ] 

- [ ] garipott10@mail.ru

**Comment by TheGoldenCactus11** [comment]
Hi,

This github is for Discord Games and SDK, I recommend checking https://dis.gd/contact instead since we can't help here. But on a quick note, you entered gmail.ru, when your email is gmail.com.

Beat everyone to it this time lol.
