### ISSUE TITLE
[Feature Request] In-app purchases

### ISSUE THREAD

**Issue by rickmartensnl** [discord/gamesdk-and-dispatch#68]
Be able to make in-app purchases using the discord Game SDK. This could be useful because then you don't have to make a big backend system for purchasing in-game currency or other in-game items.

(Can't remove bug label and assignees. Sorry for the inconvenience.)

**Comment by Jump-Suit** [comment]
This is already a thing using the Store Manager. https://discord.com/developers/docs/game-sdk/store
