### ISSUE TITLE
[Feature Request] Install specific manifests

### ISSUE THREAD

**Issue by TheGoldenCactus11** [discord/gamesdk-and-dispatch#69]
Allow us to install specific manifests, for example, if we have a standalone worldbuilder as a DLC, we can just install that, without installing everything. This might be good for many reasons, considering, that dependant SKUs are installed.

**Comment by msciotti** [comment]
I believe this is already doable today? If you have a standalone worldbuilder as a DLC, you can make a separate manifest for those files and enable the manifest for only that SKU.

https://discord.com/developers/docs/dispatch/branches-and-builds#multiple-manifests-and-dlc-content

**Comment by TheGoldenCactus11** [comment]
Sorry, I was meaning, sepetate library options, under the launch options, when you have a drop-down list

**Comment by msciotti** [comment]
Oh I see. Yes, we explicitly don't support multiple library entries for the same branch. We have the dropdown play selector instead. This is intended! So this feature most likely will not happen.
