### ISSUE TITLE
Discord store page links do not embed if they are redirected

### ISSUE THREAD

**Issue by TheGoldenCactus11** [discord/gamesdk-and-dispatch#77]
**Describe the bug**
When you send links that redirect to store pages, they should embed with the game name and image, but they do not

**Steps to reproduce**
1. Have a redirect link, like a bit.ly link that goes to a store page (https://discord.com/store/skus/<appId>)
2. Send it in a Discord channel
3. It sends a standard Discord embed, not the store page embed

**Expected behavior**
It should send an embed of the game with a buy button

**Screenshots**
![image](https://user-images.githubusercontent.com/41830820/83198485-2a1c6a80-a137-11ea-998b-403ca7e88a95.png)
Links covered to not advertise. They both go to the same place

**Additional context**
I know this is not a major problem, but discord store links are long, it would be great if they could get the domain discord.store to then let devs have discord.store/gamename. Just an idea tho, since the embeds can increase the number of purchases since it has the option for a video.

**Comment by advaith1** [comment]
well it's the same for other discord service "embeds" like invites, templates, and bot invites; none show the special ui for redirects because it's shown by the client parsing the url.

**Comment by TheGoldenCactus11** [comment]
> well it's the same for other discord service "embeds" like invites, templates, and bot invites; none show the special ui for redirects because it's shown by the client parsing the url.

Fair point, it's a shame tho
