### ISSUE TITLE
iOS discord notification bug

### ISSUE THREAD

**Issue by Cyclipz** [discord/gamesdk-and-dispatch#82]
I can’t show any image proof of this bug atm but I will try and clearly explain what the bug is. So sometimes I get a ping or new unread messages in a channel and I scroll all the way down in that channel and read those messages. I sometime go to another channel or another server to chat in and I still have that ping notification or  it still says the massage(s) are/we’re unread. After looking at them. I think the most recent time this happened to me was a few days ago but I’m not 100% sure if this bug had been resolves yet.

**Comment by advaith1** [comment]
That's not related to the GameSDK or Dispatch, so it shouldn't be in this repo.

To report app bugs, go to [Discord Testers](https://discord.gg/discord-testers)
