### ISSUE TITLE
Cant see images in mobile

### ISSUE THREAD

**Issue by Randouy** [discord/gamesdk-and-dispatch#84]
![Screenshot_20200621-022851_Discord](https://user-images.githubusercontent.com/67203822/85209093-bc471580-b367-11ea-8bf9-fc3ce6d29880.jpg)
I can only see 2 images and the others is transparent, It's so weird.

**Comment by applebee1558** [comment]
This github is only for gamesdk and dispatch/game development on discord. Client bugs go to https://discord.gg/discord-testers
