### ISSUE TITLE
Can't get current user in Unity

### ISSUE THREAD

**Issue by PikiGames** [discord/gamesdk-and-dispatch#98]
I am trying to get my own username and id, but GetCurrentUser() throws an exception "ResultException: NotFound"
Please help, how do i fix this.

And yes, the sdk it self works, i tried updating my activity

**Comment by TheGoldenCactus11** [comment]
This question is better asked in the #game-sdk channel in the developer server (discord.gg/discord-developers)

Are you 100% sure you are reading https://discord.com/developers/docs/game-sdk/users#getcurrentuser right?

And, have you made sure you are using the userManager as sampled in `var user = userManager.GetCurrentUser();`

And, just one last thing:

> Before calling this function, you'll need to wait for the OnCurrentUserUpdate callback to fire after instantiating the User manager.

Are you doing this as well?

Some code samples would be good!

Thanks

**Comment by Jump-Suit** [comment]
If you followed the documentation: https://discord.com/developers/docs/game-sdk/users#getcurrentuser
In blue text it states to call the userManager.OnCurrentUserUpdate BEFORE fetching getCurrentUser!

**Comment by PikiGames** [comment]
> If you followed the documentation: https://discord.com/developers/docs/game-sdk/users#getcurrentuser
> In blue text it states to call the userManager.OnCurrentUserUpdate BEFORE fetching getCurrentUser!

Oops, I probably missed that, thanks for help
