### ISSUE TITLE
Voice Chat Issue

### ISSUE THREAD

**Issue by SkullCracker226** [discord/gamesdk-and-dispatch#99]
I don't know about iOS cause I use android, Basically I'm facing this issue since long time whenever I'm on voice chat after few minutes or sometimes I can't hear anyone in call and nobody can hear me, sometimes this happens alot but mostly once in few hours and I'm frustrated with it. Yes I have tried restarting my phone and reinstalling discord but it's still there.

**Comment by Jump-Suit** [comment]
This github repo is reserved for Discord GameSDK or Dispatch, for client bugs report them to Discord Testers.
https://discord.gg/discord-testers
